package com.hemebiotech.analytics;

import java.io.IOException;

/**
 * Goal of the interface: prepare to retrieve the collection generated by ReadSymptomDataFromFile
 */

public interface IReaderMap   {

    /**
    *If no data is available, return an empty List
    *Returns: a collection of all Symptoms retrieved by
    */

     void printFile() throws IOException;

}
